### ISSUE TITLE
NullPointerException on MuMu Emulator.

### ISSUE THREAD

**Issue by nichbar** [scwang90/SmartRefreshLayout#577] opened 2018-07-03 02:24 UTC
> Version: 1.1.0-alpha-7
> Device: MuMu Emulator (Android 4.4)

### Background

We only need refresh header so we disable load-more footer by calling `setEnableLoadMore(false)` within `onViewCreated()` callback.

### Detail
But it seems that's not the right way to disable footer. 

Here comes the detail of crash.
```
0.	java.lang.Throwable: java.lang.NullPointerException: Attempt to invoke interface method 'com.scwang.smartrefresh.layout.constant.SpinnerStyle com.scwang.smartrefresh.layout.api.RefreshInternal.getSpinnerStyle()' on a null object reference
1.	at com.scwang.smartrefresh.layout.SmartRefreshLayout$RefreshKernelImpl.a(SourceFile:3043)
2.	at com.scwang.smartrefresh.layout.SmartRefreshLayout$10$1.onAnimationUpdate(SourceFile:2648)
3.	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1463)
4.	at android.animation.ValueAnimator.animationFrame(ValueAnimator.java:1384)
5.	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1427)
6.	at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:759)
7.	at android.animation.ValueAnimator$AnimationHandler$1.run(ValueAnimator.java:801)
8.	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
9.	at android.view.Choreographer.doCallbacks(Choreographer.java:672)
10.	at android.view.Choreographer.doFrame(Choreographer.java:605)
11.	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
12.	at android.os.Handler.handleCallback(Handler.java:742)
13.	at android.os.Handler.dispatchMessage(Handler.java:95)
14.	at android.os.Looper.loop(Looper.java:157)
15.	at android.app.ActivityThread.main(ActivityThread.java:5613)
16.	at java.lang.reflect.Method.invoke(Native Method)
17.	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
18.	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
19.	com.xxx.xxx.MainActivity.onCreate(SourceFile:729)
20.	android.app.Activity.performCreate(Activity.java:6362)
21.	android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
22.	android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2441)
23.	android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2548)
24.	android.app.ActivityThread.access$1100(ActivityThread.java:154)
25.	android.app.ActivityThread$H.handleMessage(ActivityThread.java:1399)
26.	android.os.Handler.dispatchMessage(Handler.java:102)
27.	android.os.Looper.loop(Looper.java:157)
28.	android.app.ActivityThread.main(ActivityThread.java:5613)
29.	java.lang.reflect.Method.invoke(Native Method)
30.	com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
31.	com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
```

### Solution

Fix this by applying  `app:srlEnableClipFooterWhenFixedBehind = "false"` in layout xml.

But i think there should be an options to disable all footer related content completely.  : )

**Comment by scwang90** [comment] 2018-07-03 04:02
Thank you for your feedback. The problem will be fixed in the next release.

But this problem is probably caused by your incorrect use. The mRefreshFooter is not null under normal circumstances. Because the setRefreshFooter method cannot be set to null and the createRefreshFooter method cannot return null.
~~~java
public class SmartRefreshLayout {
    @Override
    public SmartRefreshLayout setRefreshFooter(@NonNull RefreshFooter footer) {
        return setRefreshFooter(footer, MATCH_PARENT, WRAP_CONTENT);
    }
}
public interface DefaultRefreshFooterCreator {
    @NonNull
    RefreshFooter createRefreshFooter(@NonNull Context context,@NonNull RefreshLayout layout);
}
~~~

The above method is marked with @NonNull.

I think the possible reason is that you returned null in the createRefreshFooter method .

like this
~~~java
        SmartRefreshLayout.setDefaultRefreshFooterCreator(new DefaultRefreshFooterCreator() {
            @NonNull
            @Override
            public RefreshFooter createRefreshFooter(@NonNull Context context, @NonNull RefreshLayout refreshLayout) {
                return null;
            }
        });
~~~

 If so, you can remove your createRefreshFooter method first.

**Comment by nichbar** [comment] 2018-07-03 10:29
Sure.
But, i don't think any code listed below would be the cause of crash.

```XML
<com.scwang.smartrefresh.layout.SmartRefreshLayout
    android:id = "@+id/refresh_layout"
    android:layout_below = "@id/refresh_hint"
    android:layout_width = "match_parent"
    android:layout_height = "match_parent">

    <com.xxx.xx.view.SwipeRefreshHeader
        android:id = "@+id/swipe_refresh_header"
        android:layout_width = "match_parent"
        android:layout_height = "40dp" />

    <android.support.v7.widget.RecyclerView
        android:id = "@+id/list_rv"
        android:layout_width = "match_parent"
        android:layout_height = "wrap_content" />
</com.scwang.smartrefresh.layout.SmartRefreshLayout>
```
```JAVA
@Override
public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
    super.onViewCreated(view, savedInstanceState);
    refreshLayout.setEnableLoadMore(false);
    refreshLayout.setOnRefreshListener(
        refreshLayout -> {
                if (!mInitRefresh) {
                    onRefresh();
                }
                mInitRefresh = false;
            }
        );
}
```

`SwipeRefreshHeader` only update itself in your `onStateChanged()` callback.

**Comment by scwang90** [comment] 2018-07-03 15:06
Version 1.1.0-alpha-10 has been released.

**Closed by scwang90** 2018-07-03 15:06 UTC
